"use strict";
//Question_24; More Conditional Tests
Object.defineProperty(exports, "__esModule", { value: true });
const Game = "Tekken 8";
const Game_2 = "GTA 6";
console.log("Equality test:", Game === Game_2);
console.log("Inequality test:", Game !== Game_2);
const Villain = "Thanos";
const Hero = "Batman";
console.log("Lowercase test:", Villain.toLowerCase() === Hero);
const Bike = "CD70";
const Bike_2 = "CD125";
console.log("Equality test:", Bike === Bike_2);
console.log("Inequality test:", Bike !== Bike_2);
console.log("Greater than test:", Bike > Bike_2);
console.log("Less than test:", Bike < Bike_2);
console.log("Greater than or equal to test:", Bike >= Bike_2);
console.log("Less than or equal to test:", Bike <= Bike_2);
const trueValue = true;
const falseValue = false;
console.log("And operator:", trueValue && falseValue);
console.log("Or operator:", trueValue || falseValue);
